### ISSUE TITLE
Cannot minimize or exit app

### ISSUE THREAD

**Issue by samkatakouzinosracing** [labtreeo/Laptics_Dash#2]
I have a few issues with this app.

Installation: Stand alone
Versions: V1.3.0, v1.3.1 

1. The app doesn't minimize when clicking the top right minimize button.
2. The app doesn't exit when clicking the top right exit button.
3. The app shows an error dialog when closing app through the taskbar
![laptics-dash_KAxU1azbmF](https://user-images.githubusercontent.com/9654814/164896274-6f857f44-007c-4a8e-ad47-28136029c4a4.png)

I've uninstalled and reinstalled a few times.
I've tried deleting leftover folders. 

Is there anything I can do to resolve this?

**Comment by labtreeo** [comment]
i will look into it thanks for the report i think that might be a bug
